plugin:
  name: Drone Rancher
  desc: Deploy builds to a Rancher orchestrated stack using rancher-compose
  type: deploy
  image: wintercircle/drone-rancher
  labels:
    - orchestration
    - deploy

pipeline:
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: wintercircle/drone-rancher
    tag: testdrone8

